SET(MCS_SEARCH_PATHS
  /usr/local
  /opt/local
  ${NINJAMCS_PATH}
  )

FIND_PATH(MCS_INCLUDE_DIR McsClass.hpp
  HINTS
  $ENV{NINJAMOMDIR}
  PATH_SUFFIXES include/ninja/momrecon include
  PATHS ${MCS_SEARCH_PATHS}
  )

FIND_LIBRARY(MCS_LIBRARY_TEMP
  NAMES Mcs
  HINTS
  $ENV{NINJAMOMDIR}
  PATH_SUFFIXES lib64/ninja/momrecon lib/ninja/momrecon
  PATHS ${MCS_SEARCH_PATHS}
  )

IF(MCS_LIBRARY_TEMP)
  SET(MCS_LIBRARY ${MCS_LIBRARY_TEMP} CACHE STRING "Where the MCS Library can be found")
  SET(MCS_LIBRARY_TEMP "${MCS_LIBRARY_TEMP}" CACHE INTERNAL "")
ENDIF(MCS_LIBRARY_TEMP)

INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(Mcs REQUIRED_VARS MCS_LIBRARY MCS_INCLUDE_DIR)